### ISSUE TITLE
Dual MST screen setup

### ISSUE THREAD

**Issue by andrejpodzimek** [CyberShadow/hax11#1] opened 2017-03-21 00:24 UTC
First of all, thanks a lot for sharing this awesome hack. I'm currently experimenting with a dual screen MST setup (two 5k monitors). I just enabled the hack by default like this:

    JoinMST=1
    MainX=0
    MainY=0
    MainW=5120
    MainH=2880
    DesktopW=10240
    DesktopH=2880
    Enable=1

The problem is that it only works correctly on the "Main" display (the left one). Windows are maximized as expected, across the entire display. The other display remains split vertically. :-( Details about my setup:
  * ArchLinux
  * 4.10.4 kernels, both custom and stock (both exhibit the same behavior)
  * xorg-xrandr 1.5.0-1
  * libx11 1.6.5-1
  * nvidia 378.13-3
  * hardware
    * `05:00.0 VGA compatible controller: NVIDIA Corporation GP104GL [Quadro P5000] (rev a1)`
    * 2x HP Z27q (on 2 DisplayPorts each, showing 5120x2880@60Hz in their monitor menus)

Additionally, although I've set the configuration above for my user account, for root and also for the `sddm` user, many things remain unaffected:
  * SDDM: login greeter on the left halves of both monitors; a weird white area covers (almost) the entire right halves
  * KDE plasmashell: split into two halves on both monitors, even on the one where windows are maximized correctly

The sddm and plasmashell problems are quite minor, but getting windows maximized correctly on both monitors whould be awesome. If you need further details, please just let me know what to tweak or what `Debug=` loglevel to use.

**Comment by CyberShadow** [comment] 2017-03-21 00:37
> The problem is that it only works correctly on the "Main" display (the left one).

This is simply because hax11 can only be configured to do MST patching for a single monitor right now... a pretty silly limitation in retrospect. I'll fix it.

> Additionally, although I've set the configuration above for my user account, for root and also for the sddm user, many things remain unaffected

For some programs, you may need to also enable `ResizeWindows`, depending on how they query monitor information (by itself `JoinMST` only affects RandR).

**Comment by CyberShadow** [comment] 2017-03-21 04:27
Can you try the latest version with this additional configuration:
```
MST2X=5120
MST2Y=0
MST2W=5120
MST2H=2880
```

**Comment by andrejpodzimek** [comment] 2017-04-15 07:19
Sorry for the delay and many thanks for the fix. I've just appended the extra settings to my configuration files. It works! Windows are maximized correctly on both monitors. (Tested with hax11-git r102.11273ca-1 on Arch.) 

Based on recent segfaults, I had to disable hax11 for the following stuff:

    /usr/bin/kapplymousetheme
    /usr/bin/kcheckrunning
    /usr/bin/plasmashell
    /usr/bin/setxkbmap
    /usr/bin/xmessage
    /usr/bin/xprop
    /usr/bin/xrandr
    /usr/bin/xrdb
    /usr/bin/xset
    /usr/bin/xsetroot
    /usr/bin/yakuake

However, there have been too many coinciding updates to my system, so some of the segfaults may have been unrelated to hax11. Also, KDE starts without compositing, but switching the compositor off and back on in `systemsettings5` restores law and order. Well, that's most likely not a hax11 issue and definitely not the recent NVidia `LD_LIBRARY_PATH` problem (or else `systemsettings5` wouldn't fix it).

I'll retry to enable hax11 for `plasmashell` and `yakuake` soon. Now that the dual-screen layout works OK for standard windowed applications, some of the special stuff might work too. (It should be easy with `yakuake`, but `plasmashell` will be troublesome, because it tries to dig monitor layout out of RandR and comes up with something bogus.

**Comment by CyberShadow** [comment] 2017-04-15 09:38
Hmm, I'm curious about those segfaults. I started working on hax11 not long before I moved from KDE to i3, but I don't think much has changed that would cause things to segfault, and some of those utilities are not KDE-specific and I definitely didn't see any segfaults with them.

In what conditions do those segfaults occur? Any chance you can attach a debugger to at least see which module they occur in?

**Comment by CyberShadow** [comment] 2022-12-11 14:38
I've made a number of fixes to hax11 since this issue was opened; I'm hoping that one of them may have addressed the cause of the segfaults you were seeing, so I'm going to close this, but we can reopen if more information surfaces. Thanks!

**Closed as not planned by CyberShadow** 2022-12-11 14:38 UTC

**Comment by andrejpodzimek** [comment] 2022-12-11 16:07
Thanks a lot for maintaining this. Yes, this worked perfectly fine for me (after the fixes) until early 2020, at which point I switched to Wayland.

Notably, this project still remains the **only** option for KDE Plasma on MST monitors; `kwin_wayland` [won’t help there yet](https://invent.kde.org/plasma/kwin/-/merge_requests/1174).
